language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: COJ+L5xJLlVIQf8+nmDJz8zmiLyqhjiwy3AkRoX5A0edaTndGgbGKUoEzOMHDkn5aJYHlv9g/w5pNuvDZZWxfMLC6SnaM9wlb6x3e4yvoeUfgwytavcCamaiiRZZxHIShzS2qlwmM36gj9gdlq3CulqqyJuC8Y68wvDp9x0MC52ZN4j/bro+3hvDEaNJGSWOLTxFK1LXWmq1+jj8qRz0BOWgBhIPi+LpDEOXvZNuQ6Mv1OnQ2zaxE5eFj9yTRZ4AmdATI946/CfpXq3DQHM0t/xROFQ96UHpjM1k6p7oBv0SvGmbCGged+tAMYGbRyEby9YhqR4tqTDOmZaROdkFaSJ0aqErGNV0JariwDsSXixhmbADeBRq9gqgkuT/6gxcJ5Skp/e3OSkKsMWnzCxTM3bfBoVbvmNbZsziCd1dExq346ImZVlkwBTTICJnjQI2RJXaXmp+Y160//JYM+J87Q+M932Q7oxMSAHx3Sj3HQYe3m4glGOSbUNVOhT5hwW3xW+BvyB5rwBctN6qMUVYUtDAWDQE8m/61o477EUFoOe/K+n7RB98G0CPuOLdV+K4165oKrIMDudoYtZBGAXldQwNS514NWAWIParaKnUBFykBopw9AyxnimMV6KibLuAGrFd1Rh2f14ZAidatIlsJCGC0m9rsrc0C1WFvkAkbk4=
  - secure: ZtafZIFC1tzkRDjMghJPIze227lDBcDDHEcqxSUtZtCd+q2Md8MQ7htbd4HZXKv0VvDtco9RzdtVwlzwnO6ROdOsMfhcXV/gRDOjCr80aVHFKDvhVkd8vDlPALa+gGk7Sm14RluQPA8syvQrHZy53K3mx8k1qYsAKTBAdzivTzZ+bAV3vigvAWPeEmnVJt31w5yciWXR6bYH7kozzPMGeDF4af61oIdBBk/FvVjWm7w4KygfZ+pCkKlPOSvtHxcKhWe7TXhc7o1rEye9IYcb48B71i5JJtqEvftxE3F+IGwOQwypkzwR03MkmFW7CGNUCF+6BzAU4lw2Ni6V54pXd7Rvg9NhA/ll2tFnoT+Gq8i33E5RyXUF3XUYob0EZ82iSEV+ed06hziM1ftiJK5sDHrM0qrSGtZQNtKLBCzikTqkbXavMMgctczBlObMIdH15mGjGAaMch+uecs10j3/cg7EfwQcxBPXSGjzCbbu8+YIOtIRUTkcMg45a5Z/3qKq60W+xHg+qpAVaT8cO+EP/B6gdC0ZrZhGbOvYsp6mx68bH5osshp2eoNoPKOjKIZ70oekGtwiUpApcixSakIosgcjZQ4L9sb52x1XJDrQhUgg0aUyZxZQBU9s8dXwN2GsBIDKGSWrvLp7IBHJ8/J7/XSJUM6agQ43J03cyUK+fdo=
